version: '3.8'

services:
  # PostgreSQL Database (chạy bằng Docker, KHÔNG phải RDS)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ecommerce-db-ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456    # <<< password của Postgres trong container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network

  # Django Backend
  backend:
    image: docker.io/nguyet2004/backend:latest
    environment:
      DEBUG: 0
      SECRET_KEY: dummy-secret-key-change-later
      DATABASE_URL: postgresql://postgres:123456@db:5432/ecommerce-db-ops
      #           user     pass   host port  db-name  (match với db ở trên)
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ecommerce-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"

  # React Frontend
  frontend:
    image: docker.io/nguyet2004/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge
